# Your full Jira instance URL
jira_url: "https://your-company.atlassian.net"

# One or more Jira usernames/account IDs to query for assigned issues
usernames:
  - "user1"
  - "user2"

# A list of board IDs to search within.
# To find board IDs: In Jira, open your board in the browser. The board ID is the
# number in the URL after "rapidView=" (e.g., ...RapidBoard.jspa?rapidView=42).
board_ids:
  - 10
  - 25
  - 42

# Set to false to disable JASPER attribution in comments
jasper_attribution: true

# --- Gemini AI Integration (Optional) ---
# Set to true to enable Gemini comment assistance.
# You will be prompted to securely store your Gemini API key on first run.
enable_gemini: false
